AWS:
  Region Name: us-west-2
  Datalake Name: oedi-data-lake
  Databases:
    - Identifier: pv_rooftops
      Name: oedi_pv_rooftops
      Locations:
        - s3://oedi-data-lake/pv-rooftop/aspects/
        - s3://oedi-data-lake/pv-rooftop/buildings/
        - s3://oedi-data-lake/pv-rooftop/developable-planes/
        - s3://oedi-data-lake/pv-rooftop/rasd/
        - s3://oedi-data-lake/pv-rooftop-pr/developable-planes/
    - Identifier: buildstock
      Name: oedi_buildstock
      Locations:
        - s3://nrel-pds-building-stock/comstock/athena/2020/comstock_v1/state
        - s3://nrel-pds-building-stock/comstock/athena/2020/comstock_v1/metadata
    - Identifier: tracking_the_sun
      Name: oedi_tracking_the_sun
      Locations:
        - s3://oedi-data-lake/tracking-the-sun/2018/
        - s3://oedi-data-lake/tracking-the-sun/2019/
        - s3://oedi-data-lake/tracking-the-sun/2020/
    - Identifier: atb
      Name: oedi_atb
      Locations:
        - s3://oedi-data-lake/ATB/electricity/parquet/2019/
        - s3://oedi-data-lake/ATB/electricity/parquet/2020/
        - s3://oedi-data-lake/ATB/electricity/parquet/2021/
    - Identifier: pvdaq
      Name: oedi_pvdaq
      Locations:
        - s3://oedi-data-lake/pvdaq/site/
        - s3://oedi-data-lake/pvdaq/system/
        - s3://oedi-data-lake/pvdaq/inverters/
        - s3://oedi-data-lake/pvdaq/meters/
        - s3://oedi-data-lake/pvdaq/metrics/
        - s3://oedi-data-lake/pvdaq/modules/
        - s3://oedi-data-lake/pvdaq/mount/
        - s3://oedi-data-lake/pvdaq/other-instruments/
        - s3://oedi-data-lake/pvdaq/pvdata/

  Staging Location: s3://replace-by-using-your-bucket/
